name: R-CMD-check

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            r-version: "4.1"
          - os: ubuntu-latest
            r-version: "release"

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::rmarkdown
            any::knitr
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2
        with:
          upload-snapshots: true
